#!/usr/bin/env python3
"""
Extract 2D slices from real-subtomogram stacks for SPA-style 2D classification.

This script reads the particles_for_class2d.star file generated by 
relion_tomo_subtomo with --real_subtomo, extracts the specified slice from 
each .mrc file (one per subtomogram), and creates one .mrcs particle stack 
per tomogram position with a proper SPA-compatible STAR file.

Input structure:
    Extract/job024/Subtomograms/Position_*/particle_*.mrc (one 2D stack per subtomo)
    
Output structure:
    output_dir/Position_*.mrcs (one particle stack per position)
    output_dir/particles.star (STAR file referencing all particles)

Usage:
    python extract_2d_for_classification.py \
        --i Extract/job024/particles_for_class2d.star \
        --o Class2D_prep/particles
"""

import argparse
import os
import re
import numpy as np
import mrcfile
from pathlib import Path
from collections import defaultdict
from scipy.spatial.transform import Rotation as R


def parse_star_file(star_path):
    """Parse a RELION STAR file and return data blocks as dictionaries."""
    
    blocks = {}
    current_block = None
    current_headers = []
    current_data = []
    in_loop = False
    
    with open(star_path, 'r') as f:
        for line in f:
            line = line.strip()
            
            # Skip empty lines and comments outside of data
            if not line or line.startswith('#'):
                continue
            
            # New data block
            if line.startswith('data_'):
                # Save previous block if exists
                if current_block is not None and current_headers:
                    blocks[current_block] = {
                        'headers': current_headers,
                        'data': current_data
                    }
                current_block = line[5:]  # Remove 'data_' prefix
                current_headers = []
                current_data = []
                in_loop = False
                continue
            
            # Loop indicator
            if line == 'loop_':
                in_loop = True
                continue
            
            # Header line (starts with _rln)
            if line.startswith('_rln'):
                parts = line.split()
                header_name = parts[0]
                current_headers.append(header_name)
                continue
            
            # Data line (if we have headers)
            if in_loop and current_headers and not line.startswith('_'):
                parts = line.split()
                if len(parts) >= len(current_headers):
                    current_data.append(parts[:len(current_headers)])
    
    # Save last block
    if current_block is not None and current_headers:
        blocks[current_block] = {
            'headers': current_headers,
            'data': current_data
        }
    
    return blocks


def write_star_file(output_path, optics_block, particles_block):
    """Write a RELION 3.1+ style STAR file."""
    
    with open(output_path, 'w') as f:
        # Write optics block
        f.write('\n# version 30001\n\n')
        f.write('data_optics\n\n')
        f.write('loop_\n')
        for i, header in enumerate(optics_block['headers']):
            f.write(f'{header} #{i+1}\n')
        for row in optics_block['data']:
            f.write(' '.join(row) + '\n')
        
        f.write('\n\n')
        
        # Write particles block
        f.write('data_particles\n\n')
        f.write('loop_\n')
        for i, header in enumerate(particles_block['headers']):
            f.write(f'{header} #{i+1}\n')
        for row in particles_block['data']:
            f.write(' '.join(row) + '\n')


def main():
    parser = argparse.ArgumentParser(
        description='Extract 2D slices from real-subtomogram stacks for 2D classification'
    )
    parser.add_argument('--i', required=True, help='Input particles_for_class2d.star file')
    parser.add_argument('--o', required=True, help='Output directory (will create .mrcs files and particles.star)')
    parser.add_argument('--normalize', action='store_true', 
                        help='Normalize particles (subtract mean, divide by stddev)')
    parser.add_argument('--invert', action='store_true',
                        help='Invert contrast (multiply by -1)')
    parser.add_argument('--bg_radius', type=int, default=None,
                        help='Radius for background estimation (pixels from edge)')
    
    args = parser.parse_args()
    
    # Parse input STAR file
    print(f"Reading {args.i}...")
    blocks = parse_star_file(args.i)
    
    if 'optics' not in blocks or 'particles' not in blocks:
        raise ValueError("STAR file must contain 'optics' and 'particles' blocks")
    
    optics = blocks['optics']
    particles = blocks['particles']
    
    # Find the image name column
    try:
        img_idx = particles['headers'].index('_rlnImageName')
    except ValueError:
        raise ValueError("Could not find _rlnImageName column in particles block")
    
    # Create output directory
    output_dir = args.o
    os.makedirs(output_dir, exist_ok=True)
    
    # Group particles by Position folder
    print(f"Grouping {len(particles['data'])} particles by position...")
    
    position_particles = defaultdict(list)  # position_name -> [(row_idx, slice_idx, filepath, row_data), ...]
    
    for row_idx, row in enumerate(particles['data']):
        img_name = row[img_idx]
        
        # Parse slice@filename format
        if '@' in img_name:
            slice_str, filepath = img_name.split('@', 1)
            slice_idx = int(slice_str) - 1  # Convert to 0-based index
        else:
            filepath = img_name
            slice_idx = 0
        
        # Extract position name from path (e.g., "Position_01" from ".../Subtomograms/Position_01/...")
        match = re.search(r'(Position_[^/]+)', filepath)
        if match:
            position_name = match.group(1)
        else:
            # Fallback: use parent directory name
            position_name = Path(filepath).parent.name
        
        position_particles[position_name].append((row_idx, slice_idx, filepath, row))
    
    print(f"Found {len(position_particles)} positions")
    
    # Process each position
    new_particle_data = [None] * len(particles['data'])  # Preserve original order
    
    for position_name, particle_list in sorted(position_particles.items()):
        print(f"  Processing {position_name} ({len(particle_list)} particles)...")
        
        position_images = []
        
        for row_idx, slice_idx, filepath, row in particle_list:
            if not os.path.exists(filepath):
                print(f"    Warning: File not found: {filepath}")
                continue
            
            # Open MRC file and extract slice
            # Use permissive=True to handle 16-bit float (mode 12) files from RELION
            with mrcfile.open(filepath, mode='r', permissive=True) as mrc:
                data = mrc.data
                if data is None:
                    print(f"    Warning: Could not read data from {filepath}")
                    continue
                # Ensure data is float32 for proper handling
                data = np.array(data, dtype=np.float32)
                if data.ndim == 3:
                    if slice_idx >= data.shape[0]:
                        print(f"    Warning: Slice {slice_idx} out of range for {filepath}")
                        continue
                    img = data[slice_idx].copy()
                elif data.ndim == 2:
                    img = data.copy()
                else:
                    print(f"    Warning: Unexpected data dimensions in {filepath}")
                    continue
            
            # Apply normalization if requested
            if args.normalize:
                if args.bg_radius is not None:
                    # Estimate background from edges
                    cy, cx = img.shape[0] // 2, img.shape[1] // 2
                    y, x = np.ogrid[:img.shape[0], :img.shape[1]]
                    r = np.sqrt((x - cx)**2 + (y - cy)**2)
                    mask = r > (min(img.shape) // 2 - args.bg_radius)
                    bg_mean = img[mask].mean()
                    bg_std = img[mask].std()
                else:
                    bg_mean = img.mean()
                    bg_std = img.std()
                
                if bg_std > 0:
                    img = (img - bg_mean) / bg_std
            
            # Invert contrast if requested
            if args.invert:
                img = -img
            
            position_images.append(img.astype(np.float32))
            
            # Update row with new image name (1-indexed slice in position stack)
            new_row = row.copy()
            output_mrcs = os.path.join(output_dir, f"{position_name}.mrcs")
            new_row[img_idx] = f"{len(position_images)}@{output_mrcs}"
            new_particle_data[row_idx] = new_row
        
        # Write position stack
        if position_images:
            output_mrcs = os.path.join(output_dir, f"{position_name}.mrcs")
            stack = np.stack(position_images, axis=0)
            with mrcfile.new(output_mrcs, overwrite=True) as mrc:
                mrc.set_data(stack)
                # Set space group to 0 for image stack (not volume)
                mrc.header.ispg = 0
                # Set mz to 1 to indicate 2D images, not a 3D volume
                mrc.header.mz = 1
                # Set pixel size from optics if available
                try:
                    ps_idx = optics['headers'].index('_rlnImagePixelSize')
                    pixel_size = float(optics['data'][0][ps_idx])
                    mrc.voxel_size = pixel_size
                except (ValueError, IndexError):
                    pass
            print(f"    Wrote {output_mrcs} ({len(position_images)} particles)")
    
    # Remove None entries (particles that couldn't be processed)
    new_particle_data = [row for row in new_particle_data if row is not None]
    
    print(f"\nTotal particles extracted: {len(new_particle_data)}")
    
    if len(new_particle_data) == 0:
        raise ValueError("No particles were extracted!")
    
    # Modify optics block for 2D SPA data
    spa_optics_headers = [
        '_rlnOpticsGroupName',
        '_rlnOpticsGroup', 
        '_rlnImagePixelSize',
        '_rlnImageSize',
        '_rlnImageDimensionality',
        '_rlnVoltage',
        '_rlnSphericalAberration',
        '_rlnAmplitudeContrast',
    ]
    
    new_optics_headers = []
    for header in spa_optics_headers:
        if header in optics['headers']:
            new_optics_headers.append(header)
    
    # Build new optics data rows - keep ALL optics groups from input
    new_optics_data = []
    for orig_row in optics['data']:
        new_optics_row = []
        for header in new_optics_headers:
            idx = optics['headers'].index(header)
            value = orig_row[idx]
            # Force dimensionality to 2
            if header == '_rlnImageDimensionality':
                value = '2'
            new_optics_row.append(value)
        new_optics_data.append(new_optics_row)
    
    new_optics = {
        'headers': new_optics_headers,
        'data': new_optics_data
    }
    
    print(f"Kept {len(new_optics_data)} optics groups")
    
    # Convert tomo ZYZ angles to SPA ZYZ angles
    # The tomo angles rotate the filament to be parallel to the X-axis
    # We need angles that rotate the filament to be parallel to the Z-axis
    # This requires pre-multiplying by R_y(-90°) which takes X to Z
    # R_new = R_y(-90°) * R_ZYZ(rot, tilt, psi)
    
    def convert_tomo_to_spa_angles(rot, tilt, psi):
        """
        Convert tomo ZYZ Euler angles (filament -> X-axis) to SPA ZYZ angles (filament -> Z-axis).
        
        Args:
            rot, tilt, psi: ZYZ Euler angles in degrees
            
        Returns:
            new_rot, new_tilt, new_psi: New ZYZ Euler angles in degrees, wrapped to [-180, 180]
        """
        # Create the original ZYZ rotation
        rot_original = R.from_euler('zyz', [psi, tilt, rot], degrees=True)
        
        # Rotation that takes Y-axis to Z-axis: -90° around Y
        rot_x_minus90 = R.from_euler('x', -90, degrees=True)
        
        # Compose: R_new = R_y(-90) * R_original
        rot_new = rot_x_minus90 * rot_original
        
        # Extract new ZYZ angles (scipy returns rot,psi in [-180,180], tilt in [0,180])
        new_psi, new_tilt, new_rot = rot_new.as_euler('zyz', degrees=True)
                
        return new_rot, new_tilt, new_psi
    
    # Get indices for source tomo angles
    tomo_angle_indices = {}
    for tomo_col in ['_rlnTomoSubtomogramRot', '_rlnTomoSubtomogramTilt', '_rlnTomoSubtomogramPsi']:
        if tomo_col in particles['headers']:
            tomo_angle_indices[tomo_col] = particles['headers'].index(tomo_col)
    
    # Check if we have all three tomo angles
    has_all_tomo_angles = all(col in tomo_angle_indices for col in 
                              ['_rlnTomoSubtomogramRot', '_rlnTomoSubtomogramTilt', '_rlnTomoSubtomogramPsi'])
    
    if has_all_tomo_angles:
        rot_idx = tomo_angle_indices['_rlnTomoSubtomogramRot']
        tilt_idx = tomo_angle_indices['_rlnTomoSubtomogramTilt']
        psi_idx = tomo_angle_indices['_rlnTomoSubtomogramPsi']
        
        # Add SPA angle columns
        spa_cols = ['_rlnAngleRot', '_rlnAngleTilt', '_rlnAnglePsi', 
                    '_rlnAngleTiltPrior', '_rlnAnglePsiPrior']
        
        for spa_col in spa_cols:
            if spa_col not in particles['headers']:
                particles['headers'].append(spa_col)
        
        # Get column indices for SPA angles
        spa_indices = {col: particles['headers'].index(col) for col in spa_cols}
        
        # Convert angles for each particle
        for row in new_particle_data:
            # Extend row if needed
            while len(row) < len(particles['headers']):
                row.append('0')
            
            rot = float(row[rot_idx])
            tilt = float(row[tilt_idx])
            psi = float(row[psi_idx])
            
            new_rot, new_tilt, new_psi = convert_tomo_to_spa_angles(rot, tilt, psi)
            
            row[spa_indices['_rlnAngleRot']] = f"{new_rot:.6f}"
            row[spa_indices['_rlnAngleTilt']] = f"{new_tilt:.6f}"
            row[spa_indices['_rlnAnglePsi']] = f"{new_psi:.6f}"
            row[spa_indices['_rlnAngleTiltPrior']] = f"{new_tilt:.6f}"
            row[spa_indices['_rlnAnglePsiPrior']] = f"{new_psi:.6f}"
    else:
        print("  Warning: Not all tomo angles found, skipping angle conversion")
    
    # Modify particles block - remove tomo-specific columns
    tomo_specific = [
        '_rlnTomoName',
        '_rlnTomoParticleId', 
        '_rlnTomoParticleName',
        '_rlnTomoManifoldIndex',
        '_rlnTomoSubtomogramRot',
        '_rlnTomoSubtomogramTilt',
        '_rlnTomoSubtomogramPsi',
        '_rlnCtfImage',
        '_rlnTomoVisibleFrames',
    ]
    
    keep_indices = []
    new_particle_headers = []
    for i, header in enumerate(particles['headers']):
        if header not in tomo_specific:
            keep_indices.append(i)
            new_particle_headers.append(header)
    
    # Filter particle data to keep only relevant columns
    filtered_particle_data = []
    for row in new_particle_data:
        new_row = [row[i] for i in keep_indices]
        filtered_particle_data.append(new_row)
    
    new_particles = {
        'headers': new_particle_headers,
        'data': filtered_particle_data
    }
    
    # Write output STAR file
    output_star = os.path.join(output_dir, "particles.star")
    print(f"Writing {output_star}...")
    write_star_file(output_star, new_optics, new_particles)
    
    print(f"\nDone! Created:")
    print(f"  {len(position_particles)} position stacks in {output_dir}/")
    print(f"  {output_star} ({len(filtered_particle_data)} particles)")
    print(f"\nYou can now run 2D classification with:")
    print(f"  relion_refine --i {output_star} --o Class2D/run --K 50 --iter 25 --tau2_fudge 2 ...")


if __name__ == '__main__':
    main()
