#!/bin/bash  
TOMONAME=Position_60_4
ROOT=/mnt/storage/data/users/lukas/20251127_MSA_liftout/Session1/msa_human/20251127_lift_out/Position_60_4
REPOSITORY=/mnt/storage/data/users/lukas/subtomo-averaging
ANGPIX=1.98 # make sure it is a float, e.g. 2.00 (not 2)
MAGNIFICATION=64000
FRAMEEXPOSURE=3.4
RECBINNING=4
BOXSIZE=64
TOMOSIZEX=4096
TOMOSIZEY=4096
TOMOSIZEZ=3000
MOTIONCOR_EXECUTABLE=/programs/x86_64-linux/system/sbgrid_bin/MotionCor2_1.6.4_Cuda112_Mar312023


echo "TOMONAME: $TOMONAME"
echo "ROOT: $ROOT"
echo "REPOSITORY: $REPOSITORY"
echo "ANGPIX: $ANGPIX"
echo "MAGNIFICATION: $MAGNIFICATION"
echo "FRAMEEXPOSURE: $FRAMEEXPOSURE"
echo "RECBINNING: $RECBINNING"
echo "BOXSIZE: $BOXSIZE"
echo "TOMOSIZEX: $TOMOSIZEX"
echo "TOMOSIZEY: $TOMOSIZEY"
echo "TOMOSIZEZ: $TOMOSIZEZ"
echo "MOTIONCOR_EXECUTABLE: $MOTIONCOR_EXECUTABLE"